export type Location = {
  slug: string;
  name: string;
  fullName: string;
  type: "city" | "neighborhood" | "town" | "mountain";
  county: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  neighborhoods: string[];
  landmarks: string[];
};

export const locations: Location[] = [
  {
    slug: "tucson",
    name: "Tucson",
    fullName: "Tucson, AZ",
    type: "city",
    county: "Pima County",
    metaTitle: "Junk Removal Tucson AZ | Same-Day Hauling | Haul It Off",
    metaDescription: "Tucson's veteran-owned junk removal team. Same-day pickup, upfront pricing, eco-friendly disposal. Family-owned and locally trusted. (520) 808-2268.",
    intro: "Tucson is home. From the foothills off Sabino Canyon to the downtown blocks along Congress Street, our trucks roll across every Tucson zip code seven days a week. Whether you're off Speedway, near 4th Avenue, or out by Davis-Monthan, we'll have a crew at your door fast.",
    neighborhoods: ["Sam Hughes", "El Encanto", "Armory Park", "Barrio Viejo", "Menlo Park", "Iron Horse", "West University", "Dunbar Spring", "Palo Verde", "Pantano East", "Catalina Vista", "Civano"],
    landmarks: ["University of Arizona", "Sabino Canyon", "Saguaro National Park", "Davis-Monthan AFB", "Tucson Mountain Park", "Reid Park Zoo", "Mission San Xavier del Bac", "Tucson Convention Center"],
  },
  {
    slug: "oro-valley",
    name: "Oro Valley",
    fullName: "Oro Valley, AZ",
    type: "city",
    county: "Pima County",
    metaTitle: "Junk Removal Oro Valley AZ | Same-Day Pickup | Haul It Off",
    metaDescription: "Oro Valley junk removal, cleanouts, and light demolition. Veteran-owned crew serving the Pusch Ridge area along Oracle Rd. (520) 808-2268.",
    intro: "Oro Valley sits at the foot of Pusch Ridge, and our home base on N Oracle Road means we're often there inside the hour. From Rancho Vistoso up to the Tortolitas, we handle clean-outs, junk pickups, and yard waste hauls across every Oro Valley neighborhood.",
    neighborhoods: ["Rancho Vistoso", "Sun City Vistoso", "Stone Canyon", "La Cholla Airpark", "Pusch Ridge Vistas", "Canada Hills", "Copper Creek", "Vistoso Highlands", "Honeybee Ridge"],
    landmarks: ["Catalina State Park", "Pusch Ridge", "Oro Valley Marketplace", "Steam Pump Ranch", "Honeybee Canyon Park", "Tohono Chul Park"],
  },
  {
    slug: "marana",
    name: "Marana",
    fullName: "Marana, AZ",
    type: "city",
    county: "Pima County",
    metaTitle: "Junk Removal Marana AZ | Dove Mountain & Continental Ranch | Haul It Off",
    metaDescription: "Marana junk removal and cleanouts. Serving Dove Mountain, Continental Ranch, and all of northwest Tucson metro. (520) 808-2268.",
    intro: "Marana stretches from Continental Ranch on I-10 up into Dove Mountain and the Tortolita foothills. Our crews roll through the Twin Peaks corridor and out toward Avra Valley daily — junk pickup, garage clean-outs, light demo, all of it.",
    neighborhoods: ["Dove Mountain", "Continental Ranch", "Continental Reserve", "Gladden Farms", "Sanders Grove", "Tangerine Crossing", "Twin Peaks", "Saguaro Bloom"],
    landmarks: ["Ritz-Carlton Dove Mountain", "Tortolita Mountains", "Marana Regional Airport", "Sanders Grove Park", "Crooked Tree Golf Course"],
  },
  {
    slug: "vail",
    name: "Vail",
    fullName: "Vail, AZ",
    type: "city",
    county: "Pima County",
    metaTitle: "Junk Removal Vail AZ | Rita Ranch & Civano | Haul It Off",
    metaDescription: "Vail AZ junk removal, cleanouts, and demolition. Serving Rita Ranch, Rancho del Lago, Civano, and southeast Tucson. (520) 808-2268.",
    intro: "Vail keeps growing — Rancho del Lago, Del Webb at Rancho del Lago, Rita Ranch — and our trucks know every cul-de-sac along Old Spanish Trail and Houghton. Same-day junk hauling and clean-outs across the southeast valley.",
    neighborhoods: ["Rancho del Lago", "Del Webb at Rancho del Lago", "Rita Ranch", "Sycamore Canyon", "Mountain Vail Estates", "Saguaro Ranch", "Civano"],
    landmarks: ["Cienega Creek", "Colossal Cave Mountain Park", "Old Vail Post Office", "Pantano Wash", "Mica Mountain"],
  },
  {
    slug: "sahuarita",
    name: "Sahuarita",
    fullName: "Sahuarita, AZ",
    type: "city",
    county: "Pima County",
    metaTitle: "Junk Removal Sahuarita AZ | Rancho Sahuarita | Haul It Off",
    metaDescription: "Sahuarita and Quail Creek junk removal. Fast scheduling, eco-friendly hauling, fully insured. (520) 808-2268.",
    intro: "Sahuarita sits along I-19 south of Tucson, with Rancho Sahuarita and Quail Creek anchoring the community. Whether you're clearing out a garage on La Cañada or doing a full move-out off Sahuarita Boulevard, our crew is a short trip away.",
    neighborhoods: ["Rancho Sahuarita", "Quail Creek", "Madera Highlands", "Sahuarita Highlands", "Las Campanas", "Country Park"],
    landmarks: ["Sahuarita Lake", "Quail Creek Country Club", "Madera Canyon", "Anamax Park", "Sahuarita Town Center"],
  },
  {
    slug: "green-valley",
    name: "Green Valley",
    fullName: "Green Valley, AZ",
    type: "town",
    county: "Pima County",
    metaTitle: "Junk Removal Green Valley AZ | Senior-Friendly Hauling | Haul It Off",
    metaDescription: "Green Valley AZ junk removal and clean-outs. Patient, respectful crews. Estate and downsize specialists. (520) 808-2268.",
    intro: "Green Valley is full of retirees who deserve a calm, respectful crew when it's time to downsize or clear out. We slow down, listen, and handle every estate and downsize cleanout with care — from La Posada to Canoa Ranch.",
    neighborhoods: ["La Posada", "Canoa Ranch", "Las Campanas", "Desert Hills", "Country Club Estates", "Casas del Sur", "Vista Hermosa"],
    landmarks: ["Green Valley Recreation", "Titan Missile Museum", "Madera Canyon", "San Xavier Mission (south view)", "Canoa Ranch Golf Resort"],
  },
  {
    slug: "catalina-foothills",
    name: "Catalina Foothills",
    fullName: "Catalina Foothills, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Catalina Foothills | Tucson | Haul It Off AZ",
    metaDescription: "Catalina Foothills junk removal and luxury home cleanouts. Discreet crews, careful with finishes. (520) 808-2268.",
    intro: "The Foothills have winding driveways, gated entries, and homes that take careful handling. Our crews are trained to protect tile, hardwoods, and custom cabinetry on every Catalina Foothills job.",
    neighborhoods: ["Skyline Country Club", "Finisterra", "Cobblestone", "Sabino Mountain", "Pima Canyon Estates", "Ventana Canyon"],
    landmarks: ["La Encantada", "Sabino Canyon", "Skyline Country Club", "Ventana Canyon Resort", "Loews Ventana Canyon"],
  },
  {
    slug: "casas-adobes",
    name: "Casas Adobes",
    fullName: "Casas Adobes, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Casas Adobes | NW Tucson | Haul It Off",
    metaDescription: "Casas Adobes junk pickup, garage cleanouts, and yard waste hauling in northwest Tucson. (520) 808-2268.",
    intro: "Casas Adobes anchors the Oracle and Ina corridor in northwest Tucson — older homes, mature trees, and lots of yard debris during monsoon. We're up here daily.",
    neighborhoods: ["Casas Adobes Estates", "Northwest Estates", "Tucson Estates North", "Oracle View", "La Cholla Hills"],
    landmarks: ["Foothills Mall area", "Casas Adobes Plaza", "Northwest Medical Center", "Christina-Taylor Green Memorial River Park"],
  },
  {
    slug: "tanque-verde",
    name: "Tanque Verde",
    fullName: "Tanque Verde, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Tanque Verde | East Tucson | Haul It Off",
    metaDescription: "Tanque Verde junk removal and demolition services. Serving the east Tucson foothills. (520) 808-2268.",
    intro: "Tanque Verde runs east toward the Rincons — bigger lots, more outdoor storage, plenty of saguaro trim and yard work to haul. We know every back road from Snyder to Redington Pass.",
    neighborhoods: ["Tanque Verde Valley", "Bear Canyon", "Wentworth Estates", "Saddlebrook Ranch", "Pantano Trails"],
    landmarks: ["Tanque Verde Ranch", "Redington Pass", "Saguaro National Park East", "Agua Caliente Park"],
  },
  {
    slug: "rita-ranch",
    name: "Rita Ranch",
    fullName: "Rita Ranch, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Rita Ranch | SE Tucson | Haul It Off",
    metaDescription: "Rita Ranch and southeast Tucson junk removal. Same-day appointments along Houghton & Valencia. (520) 808-2268.",
    intro: "Rita Ranch fills the corner between Houghton, Valencia, and Old Vail Road — newer builds, tight HOAs, and lots of cleanouts at move-in and move-out. We work fast and clean.",
    neighborhoods: ["Rita Ranch", "Mesquite Ranch", "Saguaro Ranch", "Esmond Station", "Civano"],
    landmarks: ["Pima Community College East", "Cienega High School", "Houghton Town Center", "Esmond Station K-8"],
  },
  {
    slug: "corona-de-tucson",
    name: "Corona de Tucson",
    fullName: "Corona de Tucson, AZ",
    type: "town",
    county: "Pima County",
    metaTitle: "Junk Removal Corona de Tucson | Haul It Off AZ",
    metaDescription: "Corona de Tucson junk removal and cleanouts. Serving Vail Valley and Sycamore Canyon. (520) 808-2268.",
    intro: "Corona de Tucson is quiet, custom-home country at the foot of the Santa Ritas. Bigger lots mean bigger shed and fence demos — and we love that work.",
    neighborhoods: ["Sycamore Canyon", "Empirita", "Mountain Vail Estates", "Hilltop Vista"],
    landmarks: ["Santa Rita Mountains", "Cienega Creek Natural Preserve", "Corona de Tucson Library", "Sycamore Canyon Trail"],
  },
  {
    slug: "saddlebrooke",
    name: "SaddleBrooke",
    fullName: "SaddleBrooke, AZ",
    type: "town",
    county: "Pinal County",
    metaTitle: "Junk Removal SaddleBrooke AZ | Retirement Community | Haul It Off",
    metaDescription: "SaddleBrooke senior-friendly junk removal and estate cleanouts. Patient, respectful, fully insured crews. (520) 808-2268.",
    intro: "SaddleBrooke is one of the best 55+ communities in the state, and we love working up here. Downsizing, estate cleanouts, garage clears — we move at the homeowner's pace.",
    neighborhoods: ["SaddleBrooke One", "SaddleBrooke TWO", "SaddleBrooke Ranch", "Preserve at SaddleBrooke"],
    landmarks: ["SaddleBrooke Ranch Golf Club", "MountainView Country Club", "DesertView Performing Arts Center", "Catalina Mountains"],
  },
  {
    slug: "picture-rocks",
    name: "Picture Rocks",
    fullName: "Picture Rocks, AZ",
    type: "town",
    county: "Pima County",
    metaTitle: "Junk Removal Picture Rocks AZ | Haul It Off",
    metaDescription: "Picture Rocks and Tucson Mountains junk removal. Rural-friendly crews, long driveways no problem. (520) 808-2268.",
    intro: "Picture Rocks sits west of the Tucson Mountains — rural lots, dirt roads, and plenty of outdoor projects. Bring it on; we don't shy away from the long driveways.",
    neighborhoods: ["Picture Rocks", "Tucson Mountain Estates", "Sandario", "Rillito Hills"],
    landmarks: ["Saguaro National Park West", "Arizona-Sonora Desert Museum", "Tucson Mountain Park", "Old Tucson Studios"],
  },
  {
    slug: "drexel-heights",
    name: "Drexel Heights",
    fullName: "Drexel Heights, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Drexel Heights | SW Tucson | Haul It Off",
    metaDescription: "Drexel Heights junk removal and clean-outs. Fast pickups across southwest Tucson. (520) 808-2268.",
    intro: "Drexel Heights covers southwest Tucson between San Xavier and Cardinal — a mix of older neighborhoods and newer builds, and lots of garage cleanouts on weekends.",
    neighborhoods: ["Drexel Park", "Bopp Estates", "Mission Hills", "Casa Verde"],
    landmarks: ["Mission San Xavier del Bac", "Tucson International Airport", "Drexel Park"],
  },
  {
    slug: "flowing-wells",
    name: "Flowing Wells",
    fullName: "Flowing Wells, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Flowing Wells | NW Tucson | Haul It Off",
    metaDescription: "Flowing Wells junk pickup, garage cleanouts, and yard hauling. (520) 808-2268.",
    intro: "Flowing Wells runs along Miracle Mile and northwest Tucson — established homes, lots of established stuff in those garages. We can fix that today.",
    neighborhoods: ["Flowing Wells", "Romero Park", "Pueblo Vista", "Sycamore Park"],
    landmarks: ["Tucson Mall", "Flowing Wells Park", "Roger Road Recreation"],
  },
  {
    slug: "tucson-estates",
    name: "Tucson Estates",
    fullName: "Tucson Estates, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Tucson Estates | West Tucson | Haul It Off",
    metaDescription: "Tucson Estates junk hauling, cleanouts, and yard debris removal in west Tucson. (520) 808-2268.",
    intro: "Tucson Estates is a 55+ favorite west of I-10 along Ajo Way — mobile homes, parkside lots, and lots of downsize work. We bring the patience.",
    neighborhoods: ["Tucson Estates I", "Tucson Estates II", "Diamond Bell Ranch"],
    landmarks: ["Tucson Estates Community Center", "Tucson Mountains", "Snyder Hill"],
  },
  {
    slug: "three-points",
    name: "Three Points",
    fullName: "Three Points, AZ",
    type: "town",
    county: "Pima County",
    metaTitle: "Junk Removal Three Points AZ | Haul It Off",
    metaDescription: "Three Points and Robles Junction junk removal. Rural Pima County hauling. (520) 808-2268.",
    intro: "Three Points (Robles Junction) sits along Ajo Highway west of Tucson — wide open desert and big residential lots. We'll bring the right trailer for the job.",
    neighborhoods: ["Robles Junction", "Diamond Bell Ranch", "Quijotoa", "Coyote"],
    landmarks: ["Kitt Peak National Observatory road", "Coyote Mountains Wilderness", "Sandario Road corridor"],
  },
  {
    slug: "avra-valley",
    name: "Avra Valley",
    fullName: "Avra Valley, AZ",
    type: "town",
    county: "Pima County",
    metaTitle: "Junk Removal Avra Valley AZ | Haul It Off",
    metaDescription: "Avra Valley and Silverbell area junk hauling, shed demos, and ranch cleanups. (520) 808-2268.",
    intro: "Avra Valley out toward Silverbell and the Ironwoods — open lots, outbuildings, and ranch cleanups. Our crew handles the big jobs out here.",
    neighborhoods: ["Avra Valley", "Silverbell West", "Rillito Bend"],
    landmarks: ["Ironwood Forest National Monument", "Marana Regional Airport", "Silverbell Mine area"],
  },
  {
    slug: "tortolita",
    name: "Tortolita",
    fullName: "Tortolita, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Tortolita AZ | Haul It Off",
    metaDescription: "Tortolita foothills junk removal, demo, and cleanout services. (520) 808-2268.",
    intro: "Tortolita is upscale, custom-home country in the foothills north of Marana. We bring extra-careful crews and trucks built for long, scenic driveways.",
    neighborhoods: ["Dove Mountain (north)", "Tortolita Foothills", "The Highlands", "Stone Canyon (Tortolita side)"],
    landmarks: ["Tortolita Mountains", "Ritz-Carlton Dove Mountain", "Tortolita Preserve"],
  },
  {
    slug: "catalina",
    name: "Catalina",
    fullName: "Catalina, AZ",
    type: "town",
    county: "Pima County",
    metaTitle: "Junk Removal Catalina AZ | North Oro Valley | Haul It Off",
    metaDescription: "Catalina and north Oracle Rd junk removal and cleanouts. (520) 808-2268.",
    intro: "Catalina runs north along Oracle from Oro Valley toward SaddleBrooke — a great mix of homesteads, custom builds, and equestrian properties. Our crews work this corridor every week.",
    neighborhoods: ["Saddlebrooke Ranch fringe", "Highlands at Dove Mountain (east)", "Catalina Mountain Estates"],
    landmarks: ["Catalina State Park", "Romero Pools trailhead", "Biosphere 2 (nearby)"],
  },
  {
    slug: "south-tucson",
    name: "South Tucson",
    fullName: "South Tucson, AZ",
    type: "city",
    county: "Pima County",
    metaTitle: "Junk Removal South Tucson AZ | Haul It Off",
    metaDescription: "South Tucson junk pickup and clean-outs. Family-owned, neighbor-friendly. (520) 808-2268.",
    intro: "South Tucson is its own city inside Tucson — tight blocks, historic homes, and a strong neighborhood feel. We treat every South Tucson job like we're working for a neighbor, because we are.",
    neighborhoods: ["Barrio San Antonio", "Pueblo Gardens", "Sunnyside"],
    landmarks: ["Mi Nidito", "South Tucson historic district", "Pueblo Magnet High School"],
  },
  {
    slug: "summit",
    name: "Summit",
    fullName: "Summit, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Summit AZ | South Tucson | Haul It Off",
    metaDescription: "Summit and south Tucson junk removal services. (520) 808-2268.",
    intro: "Summit sits south of Tucson along the Santa Cruz River — a community we serve regularly with junk pickups, yard waste, and cleanouts.",
    neighborhoods: ["Summit", "Wilmot Valley"],
    landmarks: ["Santa Cruz River Park (south)", "San Xavier Indian Reservation (near)", "Pima Mine"],
  },
  {
    slug: "valencia-west",
    name: "Valencia West",
    fullName: "Valencia West, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Valencia West | SW Tucson | Haul It Off",
    metaDescription: "Valencia West and southwest Tucson junk hauling. (520) 808-2268.",
    intro: "Valencia West fills the corridor between San Xavier and Ajo Way — newer homes, plenty of yard projects, and our crews here daily.",
    neighborhoods: ["Valencia Crossing", "Mission Manor", "Star Valley"],
    landmarks: ["Tucson Mountains (south)", "San Xavier Mission", "Ajo Way commercial corridor"],
  },
  {
    slug: "littletown",
    name: "Littletown",
    fullName: "Littletown, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Littletown | SE Tucson | Haul It Off",
    metaDescription: "Littletown junk removal, yard hauling, and demolition. (520) 808-2268.",
    intro: "Littletown is a small unincorporated community in southeast Tucson — quiet streets, family homes, and the occasional big garage cleanout to schedule.",
    neighborhoods: ["Littletown core", "Wilmot South"],
    landmarks: ["Old Spanish Trail corridor", "Davis-Monthan AFB (near)", "Pantano Wash"],
  },
  {
    slug: "civano",
    name: "Civano",
    fullName: "Civano (East Tucson)",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Civano | East Tucson | Haul It Off",
    metaDescription: "Civano sustainable community junk removal and eco-friendly hauling. (520) 808-2268.",
    intro: "Civano is Tucson's planned sustainable community — and we love that, because our recycle/donate first model fits right in. We work this neighborhood with care.",
    neighborhoods: ["Civano I", "Civano II", "Sierra Morado"],
    landmarks: ["Civano Nursery", "Houghton Town Center", "Sierra Morado Park"],
  },
  {
    slug: "dove-mountain",
    name: "Dove Mountain",
    fullName: "Dove Mountain, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Dove Mountain | Marana | Haul It Off",
    metaDescription: "Dove Mountain luxury home cleanouts and discreet junk removal in Marana. (520) 808-2268.",
    intro: "Dove Mountain in Marana is full of custom luxury homes on big lots in the Tortolita foothills. Our crews are trained to protect every finish and stay quiet on private drives.",
    neighborhoods: ["The Highlands at Dove Mountain", "The Boulders", "The Reserve", "Saguaro Bloom (adjacent)"],
    landmarks: ["Ritz-Carlton Dove Mountain", "Dove Mountain Golf Club", "Tortolita Mountains", "Wild Burro Trail"],
  },
  {
    slug: "continental-ranch",
    name: "Continental Ranch",
    fullName: "Continental Ranch, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Continental Ranch | Marana | Haul It Off",
    metaDescription: "Continental Ranch Marana junk removal, cleanouts, and yard waste hauling. (520) 808-2268.",
    intro: "Continental Ranch anchors Marana off I-10 and Cortaro — established neighborhoods, tight cul-de-sacs, lots of weekend garage cleanouts. We're a quick trip from N Oracle.",
    neighborhoods: ["Continental Ranch", "Cortaro Ranch", "Cortaro Crossing", "Twin Peaks"],
    landmarks: ["Crossroads at Silverbell District Park", "Marana High School", "Cortaro Farms commercial"],
  },
  {
    slug: "continental-reserve",
    name: "Continental Reserve",
    fullName: "Continental Reserve, AZ",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Continental Reserve | Marana | Haul It Off",
    metaDescription: "Continental Reserve junk removal in NW Marana. (520) 808-2268.",
    intro: "Continental Reserve neighbors Continental Ranch with newer builds backing the Tucson Mountains. We do junk pickup, yard waste, and garage cleanouts up here daily.",
    neighborhoods: ["Continental Reserve", "Continental Crossings", "Silverbell Ridge"],
    landmarks: ["Silverbell Lake", "Tucson Mountain District (north)", "Continental Reserve Loop"],
  },
  {
    slug: "tubac",
    name: "Tubac",
    fullName: "Tubac, AZ",
    type: "town",
    county: "Santa Cruz County",
    metaTitle: "Junk Removal Tubac AZ | Haul It Off",
    metaDescription: "Tubac art village junk removal and estate cleanouts. (520) 808-2268.",
    intro: "Tubac is a slow-paced art village south of Green Valley along I-19 — and we serve it with the same care every gallery and adobe deserves. Schedule ahead and we'll head south.",
    neighborhoods: ["Tubac Country Club", "Barrio de Tubac", "Tubac Estates"],
    landmarks: ["Tubac Presidio State Historic Park", "Tubac Golf Resort", "Anza Trail"],
  },
  {
    slug: "benson",
    name: "Benson",
    fullName: "Benson, AZ",
    type: "town",
    county: "Cochise County",
    metaTitle: "Junk Removal Benson AZ | Haul It Off",
    metaDescription: "Benson and St. David junk hauling, demo, and cleanouts. (520) 808-2268.",
    intro: "Benson sits east of Tucson on I-10 — a friendly small town we serve for bigger projects scheduled in advance. Sheds, fences, garages, and estate work.",
    neighborhoods: ["Downtown Benson", "Pomerene", "St. David (adjacent)"],
    landmarks: ["Kartchner Caverns State Park", "San Pedro River", "Benson Visitor Center"],
  },
  {
    slug: "sonoita",
    name: "Sonoita",
    fullName: "Sonoita, AZ",
    type: "town",
    county: "Santa Cruz County",
    metaTitle: "Junk Removal Sonoita AZ | Haul It Off",
    metaDescription: "Sonoita and Elgin junk hauling, ranch cleanouts, and shed demolition. (520) 808-2268.",
    intro: "Sonoita and Elgin are wine country at 5,000 feet — open rangeland, custom homes, and barn cleanouts. We schedule out here for bigger jobs.",
    neighborhoods: ["Sonoita Crossroads", "Elgin", "Canelo Hills"],
    landmarks: ["Sonoita Vineyards", "Las Cienegas National Conservation Area", "Sonoita Fairgrounds"],
  },
  {
    slug: "catalina-state-park-area",
    name: "Catalina State Park Area",
    fullName: "Catalina State Park Area",
    type: "neighborhood",
    county: "Pima County",
    metaTitle: "Junk Removal Catalina State Park Area | Haul It Off",
    metaDescription: "Junk removal and cleanouts near Catalina State Park, north Oracle Rd. (520) 808-2268.",
    intro: "The homes ringing Catalina State Park sit right against the Santa Catalina foothills. Our base on N Oracle Rd is just down the road, so we're up here fast.",
    neighborhoods: ["Catalina foothills (state park side)", "Sanctuary Cove", "Saddlebrooke fringe"],
    landmarks: ["Catalina State Park", "Pusch Ridge", "Romero Canyon trailhead"],
  },
  {
    slug: "mt-lemmon",
    name: "Mt. Lemmon",
    fullName: "Mt. Lemmon / Summerhaven",
    type: "mountain",
    county: "Pima County",
    metaTitle: "Junk Removal Mt. Lemmon | Summerhaven | Haul It Off",
    metaDescription: "Mt. Lemmon and Summerhaven cabin cleanouts, brush hauling, and seasonal junk pickup. (520) 808-2268.",
    intro: "Summerhaven up Mt. Lemmon is a different world — cabins, pines, and seasonal projects. We schedule ahead for the Catalina Highway haul and bring the right truck for the narrow forest roads.",
    neighborhoods: ["Summerhaven Village", "Loma Linda", "Soldier Camp"],
    landmarks: ["Mt. Lemmon Ski Valley", "Cookie Cabin", "Summerhaven General Store", "Marshall Gulch"],
  },
];

export const locationsBySlug: Record<string, Location> = Object.fromEntries(locations.map((l) => [l.slug, l]));
