export type Service = {
  slug: string;
  category: "junk-removal" | "clean-outs" | "demolition" | "specialty";
  title: string;
  h1: string;
  metaTitle: string;
  metaDescription: string;
  intro: string;
  whatsIncluded: string[];
  items?: { group: string; list: string[] }[];
  relatedSlugs: string[];
  faq?: { q: string; a: string }[];
  image?: string;
};

export const services: Service[] = [
  // Hub: Junk Removal
  {
    slug: "junk-removal",
    category: "junk-removal",
    title: "Junk Removal",
    h1: "Full-Service Junk Removal in Tucson, AZ",
    metaTitle: "Tucson Junk Removal | Same-Day Pickup | Haul It Off AZ",
    metaDescription: "Fast, affordable junk removal in Tucson and across Southern Arizona. Veteran-owned, licensed & insured. Upfront pricing, same-day service. Call (520) 808-2268.",
    intro: "Tucson's go-to crew for fast, friendly junk removal. From a single couch to a packed garage, we lift, load, and haul it all so your space is clear by sundown.",
    whatsIncluded: [
      "Free on-site estimates with upfront pricing",
      "Two-person crew with truck and dollies",
      "All labor, lifting, and loading included",
      "Cleanup of the area when we're done",
      "Eco-friendly disposal — 80%+ recycled or donated",
      "Same-day and next-day appointments available",
    ],
    items: [
      {
        group: "What We Take",
        list: [
          "Old furniture and mattresses",
          "Appliances and electronics",
          "Yard waste and brush",
          "Construction debris",
          "Clothing, textiles, and household trash",
          "Carpets, rugs, and packing materials",
        ],
      },
      {
        group: "What We Don't Take",
        list: [
          "Hazardous chemicals or pesticides",
          "Medical or biological waste",
          "Asbestos materials",
          "Boats and vehicles",
          "Propane tanks (full or empty)",
          "Wet paint or oil-filled containers",
        ],
      },
    ],
    relatedSlugs: ["furniture-removal", "appliance-removal", "mattress-removal", "garage-cleanouts", "construction-debris-removal"],
    faq: [
      { q: "How fast can you get to my Tucson home?", a: "Most of the time same day or next day. Call before noon and we'll usually have a crew at your door before evening." },
      { q: "Do I need to drag the stuff to the curb?", a: "No. Just point — our crew handles every step from where the items sit. Stairs, side yards, garages, attics — we've got it." },
      { q: "How is pricing calculated?", a: "Mostly by volume in the truck (how much space your stuff takes up). We give a firm, upfront quote before we lift a finger." },
    ],
    image: "/images/HO-AZ-truck-2880w.png",
  },
  {
    slug: "furniture-removal",
    category: "junk-removal",
    title: "Furniture Removal",
    h1: "Tucson Furniture Removal & Disposal",
    metaTitle: "Furniture Removal Tucson AZ | Couches, Sofas, Dressers | Haul It Off",
    metaDescription: "Couch, sofa, sectional, dresser, table, bed frame — we haul it all. Tucson's friendly furniture removal crew. Donation and recycling first. Call (520) 808-2268.",
    intro: "Old couch in the way? Sectional that won't fit through the door? We handle every kind of furniture pickup across Tucson and Pima County — single pieces or full households.",
    whatsIncluded: [
      "Couches, sofas, sectionals, recliners",
      "Dressers, armoires, china cabinets",
      "Dining tables, chairs, bar stools",
      "Bed frames, headboards, box springs",
      "Office furniture: desks, filing cabinets, cubicles",
      "Patio and outdoor furniture",
    ],
    relatedSlugs: ["mattress-removal", "appliance-removal", "junk-removal", "estate-cleanouts"],
    faq: [
      { q: "Can you take just one piece of furniture?", a: "Absolutely. Single-item pickups are a big part of what we do. Same friendly service, no minimum charge headaches." },
      { q: "Do you donate usable furniture?", a: "Yes. Anything in good shape we route to local Tucson charities and donation centers whenever possible." },
    ],
    image: "/images/HO2-1920w.png",
  },
  {
    slug: "appliance-removal",
    category: "junk-removal",
    title: "Appliance Removal",
    h1: "Appliance Removal & Recycling in Tucson",
    metaTitle: "Appliance Removal Tucson | Refrigerator, Washer Pickup | Haul It Off AZ",
    metaDescription: "Old refrigerator, washer, dryer, stove, dishwasher pickup in Tucson. Eco-friendly recycling. Same-day service. Licensed & insured. (520) 808-2268.",
    intro: "Replacing appliances or just clearing out the old ones? Our crew safely disconnects, hauls, and recycles old appliances — including refrigerators, washers, dryers, stoves, and dishwashers.",
    whatsIncluded: [
      "Refrigerators and freezers (no Freon hassles for you)",
      "Washing machines and dryers",
      "Stoves, ovens, and ranges",
      "Dishwashers and microwaves",
      "Water heaters",
      "Small appliances and AC units",
    ],
    relatedSlugs: ["electronics-recycling", "junk-removal", "garage-cleanouts", "furniture-removal"],
    image: "/images/HO5-1920w.png",
  },
  {
    slug: "mattress-removal",
    category: "junk-removal",
    title: "Mattress Removal",
    h1: "Mattress & Box Spring Removal in Tucson",
    metaTitle: "Mattress Removal Tucson AZ | Same-Day Pickup | Haul It Off",
    metaDescription: "Old mattress pickup in Tucson, Oro Valley, Marana, Vail. Box springs, futons, bed frames hauled away. Flat-rate pricing. Call (520) 808-2268.",
    intro: "Old mattress taking up half the garage? We pick up, haul, and recycle mattresses and box springs of every size — from kid's twin to California king.",
    whatsIncluded: [
      "All sizes: twin, full, queen, king, California king",
      "Box springs and bed frames",
      "Futons and sleeper-sofa mattresses",
      "Crib and toddler mattresses",
      "Multiple mattresses (apartments, hotels, AirBnB turnover)",
    ],
    relatedSlugs: ["furniture-removal", "junk-removal", "estate-cleanouts"],
    image: "/images/IMG_1270-1920w.jpg",
  },
  {
    slug: "exercise-equipment-removal",
    category: "junk-removal",
    title: "Exercise Equipment Removal",
    h1: "Exercise & Gym Equipment Removal in Tucson",
    metaTitle: "Treadmill & Gym Equipment Removal Tucson AZ | Haul It Off",
    metaDescription: "Treadmills, ellipticals, weight benches, home gyms hauled away. Heavy equipment, no problem. Tucson & Pima County. (520) 808-2268.",
    intro: "Treadmill, elliptical, weight bench, home gym — those things are heavy and awkward. We handle disassembly, lifting, and disposal so you don't pull your back trying to do it alone.",
    whatsIncluded: [
      "Treadmills and ellipticals",
      "Stationary bikes and rowing machines",
      "Weight benches and racks",
      "Free weights, dumbbells, plates",
      "Home gyms and cable machines",
      "Disassembly included when needed",
    ],
    relatedSlugs: ["furniture-removal", "junk-removal", "garage-cleanouts"],
    image: "/images/IMG_1271-1920w.jpg",
  },
  {
    slug: "garbage-removal",
    category: "junk-removal",
    title: "Garbage Removal",
    h1: "Bulk Garbage Removal in Tucson",
    metaTitle: "Bulk Garbage Pickup Tucson AZ | Overflow Trash Removal | Haul It Off",
    metaDescription: "Missed trash day? HOA bulk pickup needed? We haul overflow trash, bagged waste, and bulky items the city won't take. Same-day service. (520) 808-2268.",
    intro: "Missed trash day, threw a big party, or finally tackled the storage room — and now you've got way more garbage than the bin will hold. We pick up the overflow same-day so you stay on the HOA's good side.",
    whatsIncluded: [
      "Overflow bags and bins",
      "HOA-compliant cleanup (avoid violations)",
      "Post-event and post-move trash",
      "Bulky items the city won't take",
      "Curbside, driveway, or backyard pickup",
      "Recurring or one-time service",
    ],
    relatedSlugs: ["junk-removal", "bulk-trash-cleanouts", "yard-debris-removal"],
    image: "/images/IMG_1272-1920w.jpg",
  },
  {
    slug: "yard-debris-removal",
    category: "junk-removal",
    title: "Yard Debris Removal",
    h1: "Yard Waste & Brush Removal in Tucson",
    metaTitle: "Yard Waste Removal Tucson AZ | Tree Branches, Brush, Leaves | Haul It Off",
    metaDescription: "Yard waste hauling in Tucson — branches, brush, leaves, palm fronds, monsoon storm debris. Same-day pickup, eco-friendly disposal. (520) 808-2268.",
    intro: "Monsoon knocked down half the yard? Palm fronds and brush piling up after a trim? We haul yard waste of every kind — bagged, bundled, or just stacked.",
    whatsIncluded: [
      "Tree branches and limbs",
      "Palm fronds and saguaro debris",
      "Leaves, grass clippings, brush",
      "Storm damage and monsoon cleanup",
      "Sod, dirt, and small landscape rock (limited)",
      "Old fence pickets and lattice (light)",
    ],
    relatedSlugs: ["construction-debris-removal", "junk-removal", "fence-removal"],
    image: "/images/Desert-1920w.png",
  },
  {
    slug: "electronics-recycling",
    category: "junk-removal",
    title: "Electronics Recycling",
    h1: "E-Waste & Electronics Recycling in Tucson",
    metaTitle: "Electronics Recycling Tucson AZ | TV, Computer Pickup | Haul It Off",
    metaDescription: "Tucson e-waste pickup: TVs, computers, monitors, printers, and more. Certified eco-friendly recycling. Keep electronics out of AZ landfills. (520) 808-2268.",
    intro: "Old TVs, monitors, and computers shouldn't go in the dumpster — they're full of materials that don't belong in the desert. We pick up e-waste and route it to certified recyclers.",
    whatsIncluded: [
      "CRT and flat-panel TVs",
      "Desktop computers, laptops, monitors",
      "Printers, scanners, copiers",
      "Servers and networking gear",
      "Phones, tablets, gaming consoles",
      "Cables, keyboards, peripherals",
    ],
    relatedSlugs: ["appliance-removal", "office-cleanouts", "junk-removal"],
    image: "/images/e-waste-704513_1280-1920w.jpg",
  },
  {
    slug: "construction-debris-removal",
    category: "junk-removal",
    title: "Construction Debris Removal",
    h1: "Construction Debris Hauling in Tucson",
    metaTitle: "Construction Debris Removal Tucson | Drywall, Concrete, Wood | Haul It Off",
    metaDescription: "Tucson construction cleanup and debris hauling for contractors, remodelers, and homeowners. Drywall, lumber, concrete, tile. (520) 808-2268.",
    intro: "Finishing a remodel? Tearing out a kitchen? We haul drywall, lumber, tile, concrete, and the rest of the mess so your job site stays clean and your crew can keep moving.",
    whatsIncluded: [
      "Drywall and plaster",
      "Lumber, framing, and trim",
      "Tile, stone, and concrete (small loads)",
      "Roofing materials and shingles",
      "Flooring, carpet, and underlayment",
      "Metal scrap and wire",
    ],
    relatedSlugs: ["interior-demolition", "commercial-junk-removal", "junk-removal"],
    image: "/images/pexels-photo-2347329-1920w.jpeg",
  },
  {
    slug: "commercial-junk-removal",
    category: "junk-removal",
    title: "Commercial Junk Removal",
    h1: "Commercial Junk Removal in Tucson",
    metaTitle: "Commercial Junk Removal Tucson | Office, Retail, Warehouse | Haul It Off",
    metaDescription: "Tucson businesses trust Haul It Off for office cleanouts, retail debris, warehouse junk removal. Licensed, insured, after-hours available. (520) 808-2268.",
    intro: "Office relocation, retail refresh, or warehouse overflow? We handle commercial junk removal for Tucson businesses with after-hours scheduling and clean, professional crews.",
    whatsIncluded: [
      "Office furniture and cubicles",
      "IT equipment and electronics",
      "Retail fixtures and displays",
      "Warehouse pallets and shrink wrap",
      "Restaurant equipment",
      "Property management and tenant turnover",
    ],
    relatedSlugs: ["office-cleanouts", "construction-debris-removal", "eviction-cleanouts"],
    image: "/images/Dumpster_HO-1920w.png",
  },

  // Hub: Clean Outs
  {
    slug: "clean-outs",
    category: "clean-outs",
    title: "Clean Outs",
    h1: "Property Clean Out Services in Tucson",
    metaTitle: "Tucson Clean Out Services | Estate, Hoarder, Storage | Haul It Off AZ",
    metaDescription: "Full-service property cleanouts in Tucson and Southern AZ. Estate, hoarder, foreclosure, storage unit, and garage cleanouts. Discreet, fast, insured. (520) 808-2268.",
    intro: "From single-room declutters to full estate clear-outs, our team handles every kind of cleanout in Tucson. We sort, lift, and haul — you walk back in to an empty, swept space.",
    whatsIncluded: [
      "Complete sort, lift, load, and haul",
      "Discreet and judgment-free service",
      "Donation routing for usable items",
      "Sweep and broom finish",
      "Photo updates while we work (if requested)",
      "Property manager and realtor coordination",
    ],
    relatedSlugs: ["estate-cleanouts", "hoarder-cleanouts", "foreclosure-cleanouts", "storage-unit-cleanouts", "garage-cleanouts"],
    image: "/images/Before-1920w.png",
  },
  {
    slug: "estate-cleanouts",
    category: "clean-outs",
    title: "Estate Cleanouts",
    h1: "Estate Cleanout Services in Tucson, AZ",
    metaTitle: "Estate Cleanouts Tucson AZ | Compassionate, Discreet | Haul It Off",
    metaDescription: "Estate cleanout services in Tucson with care and discretion. We help families, executors, and realtors clear out homes after a loss. (520) 808-2268.",
    intro: "Clearing out a loved one's home is hard. We treat every estate cleanout with respect, discretion, and patience — letting you set aside keepsakes and handling the rest.",
    whatsIncluded: [
      "Whole-house cleanout in 1–3 days",
      "Keepsake separation as you direct",
      "Donation pickups for usable items",
      "Coordination with executors and realtors",
      "Discreet crew, unmarked truck on request",
      "Final sweep and rent-ready handoff",
    ],
    relatedSlugs: ["hoarder-cleanouts", "foreclosure-cleanouts", "clean-outs", "furniture-removal"],
  },
  {
    slug: "hoarder-cleanouts",
    category: "clean-outs",
    title: "Hoarder Cleanouts",
    h1: "Hoarder House Cleanouts in Tucson",
    metaTitle: "Hoarder Cleanout Tucson AZ | Compassionate, Confidential | Haul It Off",
    metaDescription: "Compassionate hoarder cleanout services in Tucson. Discreet, judgment-free, fully insured. Restoring homes to safe, livable spaces. (520) 808-2268.",
    intro: "Hoarder cleanouts take patience and a calm crew. We move at the homeowner's pace, work judgment-free, and follow safety and sanitation best practices on every job.",
    whatsIncluded: [
      "Free, no-pressure walk-through",
      "Discreet crews and unmarked options",
      "PPE and safety protocols",
      "Biohazard-aware sorting (we partner for hazardous items)",
      "Multi-day projects welcome",
      "Coordination with family or case managers",
    ],
    relatedSlugs: ["estate-cleanouts", "clean-outs", "foreclosure-cleanouts"],
  },
  {
    slug: "foreclosure-cleanouts",
    category: "clean-outs",
    title: "Eviction & Foreclosure Cleanouts",
    h1: "Eviction & Foreclosure Cleanouts in Tucson",
    metaTitle: "Eviction & Foreclosure Cleanouts Tucson | Fast Turnaround | Haul It Off",
    metaDescription: "Rental turnover, eviction, and foreclosure cleanouts in Tucson and Southern AZ. Fast scheduling for property managers and realtors. (520) 808-2268.",
    intro: "Rentals turn fast. Foreclosures move faster. We clear tenant-left belongings, trash, and bulky items so your property is rent-ready or list-ready in days, not weeks.",
    whatsIncluded: [
      "24–48 hour scheduling for property managers",
      "Full removal: furniture, trash, appliances, debris",
      "Photo documentation before and after",
      "Coordination with realtors and landlords",
      "Lockbox / supra-key compatible",
      "Repeat-client discounts for management companies",
    ],
    relatedSlugs: ["estate-cleanouts", "commercial-junk-removal", "clean-outs"],
  },
  {
    slug: "garage-cleanouts",
    category: "clean-outs",
    title: "Garage Cleanouts",
    h1: "Garage Cleanout Services in Tucson",
    metaTitle: "Garage Cleanout Tucson AZ | Park Your Car Again | Haul It Off",
    metaDescription: "Tucson garage cleanout pros. We sort, lift, and haul years of buildup — old paint, tools, bikes, and the rest — so you can park inside again. (520) 808-2268.",
    intro: "When was the last time the car actually fit in the garage? We sort, lift, and haul the buildup so you reclaim the space — usually in a single afternoon.",
    whatsIncluded: [
      "Sort what stays vs. goes (you decide)",
      "Old tools, paint, chemicals (we route hazardous responsibly)",
      "Bikes, sports gear, holiday decor",
      "Outdated electronics and appliances",
      "Shelving teardown if needed",
      "Sweep and broom finish",
    ],
    relatedSlugs: ["basement-attic-cleanouts", "junk-removal", "clean-outs"],
  },
  {
    slug: "basement-attic-cleanouts",
    category: "clean-outs",
    title: "Attic & Storage Room Cleanouts",
    h1: "Attic, Closet & Storage Room Cleanouts in Tucson",
    metaTitle: "Attic & Storage Cleanouts Tucson | Haul It Off AZ",
    metaDescription: "Tucson attic, closet, and storage room cleanouts. We climb the ladder so you don't have to. Insured and friendly crews. (520) 808-2268.",
    intro: "Attics and storage rooms collect a lifetime of stuff. We crawl in, lift it out, and clear it — boxes of old paperwork, broken holiday lights, the giant CRT TV from 2003.",
    whatsIncluded: [
      "Attic and crawl-space cleanouts",
      "Walk-in closet declutters",
      "Linen closets and pantries",
      "Spare bedroom 'storage rooms'",
      "Old boxes and paperwork (no shredding — see commercial)",
      "Ladders and gear included",
    ],
    relatedSlugs: ["garage-cleanouts", "clean-outs", "junk-removal"],
  },
  {
    slug: "storage-unit-cleanouts",
    category: "clean-outs",
    title: "Storage Unit Cleanouts",
    h1: "Storage Unit Cleanouts in Tucson",
    metaTitle: "Storage Unit Cleanouts Tucson AZ | Stop the Monthly Fee | Haul It Off",
    metaDescription: "Tucson storage unit cleanouts — stop paying for stuff you don't need. We meet you at the unit, sort, lift, and haul. Same-day available. (520) 808-2268.",
    intro: "Paying month after month for a unit full of stuff you don't need? Unlock it, point, and we'll take care of the rest. Most units empty in 1–2 hours.",
    whatsIncluded: [
      "Meet you at any Tucson storage facility",
      "Sort what stays vs. goes on the spot",
      "All lifting and loading included",
      "Final broom-sweep so you turn keys in clean",
      "Donation routing for usable items",
      "Multiple units? No problem",
    ],
    relatedSlugs: ["estate-cleanouts", "garage-cleanouts", "clean-outs"],
  },
  {
    slug: "office-cleanouts",
    category: "clean-outs",
    title: "Office Cleanouts",
    h1: "Office & Commercial Cleanouts in Tucson",
    metaTitle: "Office Cleanouts Tucson AZ | After-Hours Available | Haul It Off",
    metaDescription: "Office cleanouts for Tucson businesses — relocations, downsizes, lease-end. After-hours and weekend scheduling. Licensed & insured. (520) 808-2268.",
    intro: "Office moves and lease-end cleanouts done after-hours so your business keeps running. We clear cubicles, IT equipment, files, and furniture — quietly and fast.",
    whatsIncluded: [
      "After-hours and weekend scheduling",
      "Cubicle and partition teardown",
      "IT equipment and e-waste handling",
      "Filing cabinets (we coordinate with shredders)",
      "Tenant improvement debris",
      "Final broom-sweep handoff",
    ],
    relatedSlugs: ["commercial-junk-removal", "electronics-recycling", "construction-debris-removal"],
  },
  {
    slug: "bulk-trash-cleanouts",
    category: "clean-outs",
    title: "Bulk Trash Cleanouts",
    h1: "Bulk Trash Pickup in Tucson",
    metaTitle: "Bulk Trash Pickup Tucson | HOA Approved | Haul It Off AZ",
    metaDescription: "Bulk trash cleanouts for Tucson homes, HOAs, and properties. We handle the heavy lifting so you stay compliant. (520) 808-2268.",
    intro: "Some loads are too big for the city pickup. We handle bulk trash for homeowners, HOAs, and property managers — one-time or recurring.",
    whatsIncluded: [
      "Single-load bulk pickup",
      "HOA compliance-friendly cleanups",
      "Post-event and post-move trash",
      "Recurring schedules for properties",
      "Photo documentation if needed",
      "Same-day in most of Tucson metro",
    ],
    relatedSlugs: ["garbage-removal", "junk-removal", "clean-outs"],
  },

  // Hub: Demolition
  {
    slug: "demolition",
    category: "demolition",
    title: "Light Demolition",
    h1: "Light Demolition Services in Tucson",
    metaTitle: "Light Demolition Tucson AZ | Shed, Deck, Interior | Haul It Off",
    metaDescription: "Tucson light demolition: sheds, decks, fences, hot tubs, kitchen and bath interior tear-outs. Tear-out plus haul-away, all in one crew. (520) 808-2268.",
    intro: "Need it gone? We tear it down. Light demolition for sheds, decks, fences, hot tubs, and interior remodel prep — and we haul every scrap when we're done.",
    whatsIncluded: [
      "Full tear-out plus haul-away in one crew",
      "Safe disconnect of utilities (when applicable)",
      "Permit guidance (we can pull or coordinate)",
      "Eco-friendly disposal of materials",
      "Property protection during demo",
      "Same-week scheduling for most jobs",
    ],
    relatedSlugs: ["shed-demolition", "hot-tub-removal", "deck-removal", "fence-removal", "interior-demolition"],
    image: "/images/HO4-9e55c51e-1920w.png",
  },
  {
    slug: "shed-demolition",
    category: "demolition",
    title: "Shed Demolition",
    h1: "Shed Demolition & Removal in Tucson",
    metaTitle: "Shed Demolition Tucson AZ | Tear-Down & Haul-Away | Haul It Off",
    metaDescription: "Tucson shed teardown and removal — wood, metal, plastic sheds. Demo plus haul-away in one stop. Termite-damaged sheds welcome. (520) 808-2268.",
    intro: "Old shed that's rotting, termite-eaten, or just in your way? Our crew tears it down and hauls it off — concrete pad option available.",
    whatsIncluded: [
      "Wood, metal, and plastic/resin sheds",
      "Storage sheds, tool sheds, mini-barns",
      "Playhouses and backyard structures",
      "Full disposal of all material",
      "Concrete pad removal (additional service)",
      "Clean, level dirt finish",
    ],
    relatedSlugs: ["deck-removal", "fence-removal", "demolition", "construction-debris-removal"],
    image: "/images/HO2-f21be245-1920w.png",
  },
  {
    slug: "hot-tub-removal",
    category: "demolition",
    title: "Hot Tub Removal",
    h1: "Hot Tub Removal & Disposal in Tucson",
    metaTitle: "Hot Tub Removal Tucson AZ | Disconnect & Haul | Haul It Off",
    metaDescription: "Hot tub removal in Tucson — disconnect, dismantle, haul, dispose. Above-ground, in-ground, inflatable, jacuzzi. Insured. (520) 808-2268.",
    intro: "Leaky, broken, or just done with it? We disconnect, dismantle, and haul away hot tubs of every type — above-ground, in-ground, jacuzzis, inflatables.",
    whatsIncluded: [
      "Electrical disconnect coordination",
      "Drainage and dismantle",
      "Cuts to fit narrow gates and side yards",
      "All hauling and disposal",
      "Cover, steps, and accessories included",
      "Eco-friendly material routing where possible",
    ],
    relatedSlugs: ["shed-demolition", "deck-removal", "demolition"],
    image: "/images/hot-tub-removal-1920w.jpg",
  },
  {
    slug: "deck-removal",
    category: "demolition",
    title: "Deck Removal",
    h1: "Deck Removal & Demolition in Tucson",
    metaTitle: "Deck Removal Tucson AZ | Wood & Composite Tear-Down | Haul It Off",
    metaDescription: "Tucson deck removal: wood, composite, rotted, or remodel-prep tear-downs. Full haul-away included. (520) 808-2268.",
    intro: "Old deck rotting, unsafe, or ready for a fresh design? We tear out wood, composite, and pressure-treated decks and haul every board away.",
    whatsIncluded: [
      "Wood, composite, and PT decks",
      "Stairs, railings, and pergolas",
      "Concrete footing removal (additional)",
      "Property protection during tear-out",
      "Full debris removal",
      "Level dirt or pad finish",
    ],
    relatedSlugs: ["shed-demolition", "fence-removal", "demolition", "construction-debris-removal"],
    image: "/images/Junk-1920w.png",
  },
  {
    slug: "fence-removal",
    category: "demolition",
    title: "Fence Removal",
    h1: "Fence Removal & Demolition in Tucson",
    metaTitle: "Fence Removal Tucson AZ | Wood, Chain-Link, Vinyl | Haul It Off",
    metaDescription: "Fence removal in Tucson and Pima County. Wood, chain-link, vinyl, metal. Tear-out plus haul. Same-week scheduling. (520) 808-2268.",
    intro: "Old fence falling over? Replacing chain-link with block? We tear out fences of every kind — wood, vinyl, chain-link, metal — and haul off every post and panel.",
    whatsIncluded: [
      "Wood pickets and stockade",
      "Chain-link and metal fence",
      "Vinyl and composite",
      "Concrete post footing removal (additional)",
      "Gate hardware included",
      "Full property cleanup",
    ],
    relatedSlugs: ["deck-removal", "shed-demolition", "yard-debris-removal", "demolition"],
  },
  {
    slug: "interior-demolition",
    category: "demolition",
    title: "Interior Demolition",
    h1: "Interior Demolition for Remodels in Tucson",
    metaTitle: "Interior Demolition Tucson AZ | Kitchen & Bath Tear-Out | Haul It Off",
    metaDescription: "Kitchen, bath, and full interior demo in Tucson. Cabinets, tile, flooring, drywall — torn out and hauled away. Renovation-ready. (520) 808-2268.",
    intro: "Gutting a kitchen, bath, or full interior for a remodel? We tear out cabinets, tile, flooring, drywall, and fixtures — and haul every piece — so your contractor walks in to a clean shell.",
    whatsIncluded: [
      "Kitchen cabinet and counter removal",
      "Bathroom vanity, tub, and tile tear-out",
      "Flooring: tile, carpet, vinyl, hardwood",
      "Drywall and ceiling demo",
      "Built-ins, closets, partitions",
      "Renovation-ready broom finish",
    ],
    relatedSlugs: ["construction-debris-removal", "demolition", "commercial-junk-removal"],
    image: "/images/Screenshot_2025-11-07_at_8.34.42-PM-1920w.png",
  },
  {
    slug: "mobile-home-demolition",
    category: "demolition",
    title: "Mobile Home Demolition",
    h1: "Mobile Home Demolition in Southern Arizona",
    metaTitle: "Mobile Home Demolition Tucson AZ | Tear-Down & Removal | Haul It Off",
    metaDescription: "Mobile home and trailer demolition in Tucson and Southern AZ. Full tear-down, disposal, lot cleanup. Free site assessment. (520) 808-2268.",
    intro: "Aging mobile home that's no longer livable? We handle full mobile home demolition and lot cleanup across Southern Arizona — single-wide, double-wide, park models.",
    whatsIncluded: [
      "Single-wide and double-wide demo",
      "Utility disconnect coordination",
      "Skirting, decks, attached structures",
      "Full debris removal and disposal",
      "Lot leveling and cleanup",
      "Free site assessment",
    ],
    relatedSlugs: ["shed-demolition", "demolition", "construction-debris-removal"],
  },
];

export const servicesBySlug: Record<string, Service> = Object.fromEntries(services.map((s) => [s.slug, s]));

export const categoryLabels: Record<Service["category"], string> = {
  "junk-removal": "Junk Removal",
  "clean-outs": "Clean Outs",
  "demolition": "Demolition",
  "specialty": "Specialty",
};
